spring.application.name=admine_management

spring.datasource.url=jdbc:postgresql://localhost:5432/queueManagement
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

# admin-service will run on port 8081
server.port=8081