spring.application.name=queue_management

spring.datasource.url=jdbc:postgresql://localhost:5432/queueManagement
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update